version: "3.8"
services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /backend
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
      - bundle:/usr/local/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  node:
    image: node:21-alpine
    container_name: node
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
      NODE_ENV: development
volumes:
  db:
    driver: local
  bundle:
    driver: local
  node:
    driver: local
